spring.application.name=stats-service
server.port=8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.client.disable-delta=true
eureka.client.registry-fetch-interval-seconds=10

management.endpoints.web.exposure.include=health,prometheus
management.endpoint.prometheus.access=unrestricted

resilience4j.circuitbreaker.instances.playerService.sliding-window-size=1
resilience4j.circuitbreaker.instances.playerService.minimum-number-of-calls=1
resilience4j.circuitbreaker.instances.playerService.failure-rate-threshold=100
resilience4j.circuitbreaker.instances.playerService.wait-duration-in-open-state=10s

resilience4j.retry.instances.playerService.max-attempts=3
resilience4j.retry.instances.playerService.wait-duration=500ms